apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret 
      containers:
      - name: udagram-api-feed
        image: klamia/udagram-api-feed:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-configmap
        env:
          - name: POSTGRESS_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: postgress_username
          - name: POSTGRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: postgress_password

        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true        
        
                

