apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-frontend
  labels:
    app: my-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-frontend
  template:
    metadata:
      labels:
        app: my-app-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: klamia/udagram-frontend:v1
        ports:
        - containerPort: 8100