apiVersion: v1
kind: Service
metadata:
  labels:
    run: udagram-api-user
  name: udagram-api-user
  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: udagram-api-user